name: CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        go: [ '1.16.x', '1.15.x' ]
        os:
        - ubuntu-latest
        - macOS-latest
        - windows-latest
    name: "Test [ Go ${{ matrix.go }}]"
    steps:
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go }}
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Test
      run: go test -v -race ./...
